version: '3'
services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=william
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rockettwitter
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432

